apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:UpzZisA7FqsjvCM6NmU2jwJo7JvO3VvMpwuPVyU3mmxnqWxUzTD477T4Vi4fU1PcXYX0ANjbUdIdCfMzBIGxMGQqv0ER8hYZL8v1atTZj4CZ3j1lFvOXigc4tKpZqirPrxd3K/4nTjFerYlnmNaPFZOUuzawu76lpK1wGn1FVyPLQVu8x2dWCjI93q3iroqCHKBulkyUindoaNZCIctAu72IrVyW1D+1FEdKq/zTFlnvTAPBZQufjWAqPmV9LT8PRBI839Ss7wvyZEZVBV8ueQy/SyFSYQAq0Tm71y9PCGiP3fFJZB9nFBXubf4=,iv:HcJxHRuCI+EzxczjLqWleLXJj8TAp7XDe1hDorBWgss=,tag:cva7A/CKwbc1yI31YL32AQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbjNmbU1CNU1PUHJId3dS
            WVpGTHhwMEF0SzZqKzRxYjd5eWZqL29vRlJZCnM1ZXZPQWRFQ3lnY3kyZ21iTEtZ
            MDdIaE9PaDFzU2NnczlzWXVuVElwVDgKLS0tIFJoclNqYzM3U1F3OEpJc2ZHaGFM
            TlNDbHhnNHhIVFFXNUl0Y3kzSHBuR2MK5AQlPPgTzUEtVYYnlnUYyBVCXgcmhntM
            LOk43ofMHchSnRaD9y+mhw3P+7bWao3UmE0meCxA2d3Iap95ynALEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T12:56:58Z"
    mac: ENC[AES256_GCM,data:UwsUfPTI5FiosazTwEQh7sgt/N2NTLItPWb0QRHKjc8SkW/mz/+pulTirKuHJpuDN4Z8AeN1u7XULtc3dXUC29iOzDFwtD3Wu/LsBtt/SoAlQFbK2qz5dpBr2BbCVMmVXMHven/HeAPEoPka6MVHzjipNvEGWddLl9DZD0GGsxM=,iv:Iw5uLOJbhw/GZX31AEIZPD/UGJEjtl1K6iajvdWgP2c=,tag:NIbcCyrj61PRUPtBSs0TwA==,type:str]
    version: 3.13.2
