apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:e/4xUQ==,iv:1MmCO+bgy9YLyN98foTyJyXC8LY3ZQ1rxH68OpqHHqw=,tag:fiaD8571KGtkRPHkDA+9aw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:HYliN1Yq64HmCtrAkkGtQQ==,iv:dohvvfJmyEhhl4RS65DtYmzshqPyHt+lcGV+5rSKrNE=,tag:Y2NeTEoVuRxFOqUs3AXgDg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS1hqUFRIREF4bUhiK0x5
            dU9waXJEWFBwYVFJUmM2bDg5TWNnZUl0cWdvCmR3ZGwrM2JCWVdSWDZPejJ4ZDd2
            RmFSdVJhcy9sMEEyUWZ1Um8zcDBjeWcKLS0tIFFWWEh2R25MV1M1eEh1V1Rzd1Ev
            Q0x4MkJHcGlzSkh2cjVaUjkveWNtVWcKOuo+Nm+m3kMFuSsyIvRocq5ZicVH3zHN
            nemdeamV0iqIL27QPag87vNDsC5u8yeAudGu9iQDkPfGohIiVOrGRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T13:19:26Z"
    mac: ENC[AES256_GCM,data:7oLhU3ALsztKEHMGVp+c4GR7RC9r8KtOmZnLa8Tpm8XD1HvDspvOq1iE6z4aj/pqFUIFRQztPybatyN/zA0ohffmWskuWoUTIPgxQOQ3QEFrJTEeSmgXtIwClDH5OS0vDAC+ZN0B+hZfXdz063P5LDEN4cF9c7+oV5P/D+fmSAI=,iv:egrr4AHGKu+//l1zz37AjHhcQwHW1JFLp7ZbimsMpBQ=,tag:mu2ggIjgETQGSUdVuIdAZA==,type:str]
    version: 3.13.2
