apiVersion: v1
data:
    password: ENC[AES256_GCM,data:rtuHPg==,iv:Wy0qDplKyuoynFjJ9av9ZzWZQnixSpSbjnoBJB+2kZk=,tag:YcbQJtsQPEjvEBhvprF+MA==,type:str]
    user: ENC[AES256_GCM,data:8Uf7oyv+0S0=,iv:lZldL07XzBO5Z/JnjHPHktlA2gZBrFoE4iltFkdePvo=,tag:2blfuic7Yga9fTa7h94JmQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q0oySWU2U2VSWDFWQytI
            bXA4dEVxajQvZ1JTYjcxR1lYYkxqT1VZY0Q0CnQvNVE5bnlxTE43cS9rR1A2Ukc0
            V1VlODlaS0NKMWhMK1Q3aWE5VTQ5VHcKLS0tIDExTkhoZjRZMkMyejdVa3VINlFy
            dFV0QzZHb0hDaDcxZVkrOUd1OFpwUVkKGNC8KCTb6uWDf8rCujB1/CuAsi0eSsER
            zSJYAJAV/qZRxlIyDYc0oAmwBBdlpT2a1kE2qYkVhhdLSQNfxNU6fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T11:57:32Z"
    mac: ENC[AES256_GCM,data:OI4d0TtkRMZeGeZD20Y4NWFWbIWOEbMlJtGLM1p6jvdEmUsSjAOthja7wd39uFV5sL1KPV+i/QrVZbmWxaJZPmYVqajsVJDcyOnLUXXEsIxppRhdmysPA+/eKns8rAcaTniUfZt42OCqWs5BPbB2z7w6uJ0/FBl2MZhHK5oh0nI=,iv:c+xoe4mgsRuS20gRbBnbpXL8R2DYWu1z7pYhLrbNYtQ=,tag:URaoPA9PF9vMmCJDfm3B1g==,type:str]
    version: 3.13.2
